-- =====================================================
-- 紧急方案：关闭所有表的 RLS（如果上面的脚本还是不行）
-- 这个方案会让所有 authenticated 用户直接访问所有表
-- =====================================================

ALTER TABLE IF EXISTS public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_models DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sales_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.logistics_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sample_deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.package_sample_follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.daily_todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.daily_reminders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.todo_remind_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customer_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customer_follow_ups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customer_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.activate_export_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cert_matrix_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cert_matrix_cells DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cert_matrix_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cert_matrix_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_certs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.package_freight_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.price_history DISABLE ROW LEVEL SECURITY;

-- 同时关闭可能存在的其他表
ALTER TABLE IF EXISTS public.customer_follow DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.certification_file DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.logistics_bill DISABLE ROW LEVEL SECURITY;

SELECT '✅ 已关闭所有表的 RLS，现在重新登录应该就能用了' as result;
